In [2]:
import numpy as np

# 生成指定维度大小（3行4列）的随机多维浮点型数据（二维），rand固定区间0.0 ~ 1.0
arr=np.random.rand(3,4)
print(arr)
print(arr.shape) # 输出一个元组，元组又一个元素表示一维，两个元素表示两维
print(arr.ndim) # 维度
print(arr.dtype) # 数据类型

[[0.45853959 0.16823841 0.97839448 0.81315381]
 [0.73756605 0.14302446 0.82590746 0.07085808]
 [0.26600257 0.33711839 0.67735998 0.73636457]]
(3, 4)
2
float64


In [3]:
# 生成指定维度大小（3行4列）的随机多维整型数据（二维），randint()可以指定区间（-1, 5）
arr = np.random.randint(-1, 5, size = (3, 4)) # 'size='可省略
print(arr)
print(type(arr))

[[4 2 4 2]
 [2 3 4 3]
 [3 0 1 0]]
<class 'numpy.ndarray'>


In [4]:
# 生成指定维度大小（3行4列）的随机多维浮点型数据（二维），uniform()可以指定区间（-1, 5）
arr = np.random.uniform(-1, 5, size = (3, 4)) # 'size='可省略
print(arr)
print(type(arr))

[[ 0.21024874  4.11184285  1.66744362  4.44686546]
 [-0.59461678  3.24079295  1.59554929  2.96651392]
 [ 3.89617881  1.18037377  1.4666057   4.18215038]]
<class 'numpy.ndarray'>


In [5]:
print('维度个数: ', arr.ndim)
print('维度大小: ', arr.shape)
print('数据类型: ', arr.dtype)

维度个数:  2
维度大小:  (3, 4)
数据类型:  float64


In [6]:
# list序列转换为 ndarray
lis = range(10)
arr = np.array(lis)

print(arr)            # ndarray数据
print(arr.ndim)        # 维度个数
print(arr.shape)    # 维度大小


[0 1 2 3 4 5 6 7 8 9]
1
(10,)


In [7]:
# list of list嵌套序列转换为ndarray
lis_lis = [range(10), range(10)]
arr = np.array(lis_lis)

print(arr)            # ndarray数据
print(arr.ndim)        # 维度个数
print(arr.shape)    # 维度大小

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
2
(2, 10)


In [8]:
arr = np.zeros((10,10,10))
print(arr.ndim)
arr = np.ones((3,3))
print(arr)

3
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
import numpy as np
arr = np.arange(15) # 15个元素一维数组
print(arr)
print(arr.reshape(3,5))
print(arr.reshape(1,3,5))

np.random.shuffle(arr)# 打乱数组
print(arr) 

arr = arr.astype(np.float16) # 转换数据类型
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
[ 1 10  6 14 11  2  3 13  9  4  7  8 12  5  0]
[ 1. 10.  6. 14. 11.  2.  3. 13.  9.  4.  7.  8. 12.  5.  0.]


In [20]:
#索引与切片
# 一位数组的的切片和索引和python中的列表类似
arr1 = np.arange(10)
print('----arr1 dtype',arr1.dtype)
print("---arr1",arr1,'----arr1[2:5]',arr1[2:5],'----arr1[1]',arr[1])

arr2 = np.arange(12).reshape(3,4)
print('---arr2 ',arr2,'\n','---type arr2',type(arr2))

print('---arr[0]',arr2[0],'---arr[0] type',type(arr2[0])) #
# arr[r1:r2, c1:c2] 【限定行的范围，限定列的范围】，如果参数是:表示取所有
print('---',arr2[0:2, :])

----arr1 dtype int64
---arr1 [0 1 2 3 4 5 6 7 8 9] ----arr1[2:5] [2 3 4] ----arr1[1] 10.0
---arr2  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 ---type arr2 <class 'numpy.ndarray'>
---arr[0] [0 1 2 3] ---arr[0] type <class 'numpy.ndarray'>
--- [[0 1 2 3]
 [4 5 6 7]]


In [16]:
year_arr = np.array([[2000, 2001, 2000],
                     [2005, 2002, 2009],
                     [2001, 2003, 2010]])

is_year_after_2005 = year_arr >= 2005
print(is_year_after_2005, is_year_after_2005.dtype)

[[False False False]
 [ True False  True]
 [False False  True]] bool


In [44]:
# 找出 data_arr 中 2005年后的数据
data_arr = np.random.rand(3,3)
print(data_arr,'\n')
filtered_arr = data_arr[is_year_after_2005] # niupi
print(filtered_arr)

[[0.67800945 0.16017176 0.36945416]
 [0.18244526 0.35573134 0.22564993]
 [0.89701835 0.51462653 0.51280962]] 

[0.18244526 0.22564993 0.51280962]


In [45]:
# 多个条件 
filtered_arr = data_arr[(year_arr <= 2005) & (year_arr % 2 == 0)]
print(filtered_arr)

[0.67800945 0.36945416 0.35573134]


In [47]:
# 矩阵转置
arr = np.random.rand(2,3)    # 2x3 数组
print(arr,'\n')    
print(arr.transpose()) # 转换为 3x2 数组

[[0.29097947 0.1048592  0.45340028]
 [0.1944405  0.37891243 0.02733774]] 

[[0.29097947 0.1944405 ]
 [0.1048592  0.37891243]
 [0.45340028 0.02733774]]


In [51]:
# 元素操作
arr = np.random.randn(2,3)

print(arr)

print('向上取整\n',np.ceil(arr)) # 向上取整

print('向下取整\n',np.floor(arr)) # 向下取整

print('四舍五入\n',np.rint(arr))

print('判断元素是不是number\n',np.isnan(arr))

print('元素相乘\n',np.multiply(arr, arr))

print('元素相除\n',np.divide(arr, arr))

print('三元运算',np.where(arr > 0, 1, -1))

[[ 0.7864322  -0.13240945  0.68908016]
 [-0.40569019 -0.23117177  0.12876485]]
向上取整
 [[ 1. -0.  1.]
 [-0. -0.  1.]]
向下取整
 [[ 0. -1.  0.]
 [-1. -1.  0.]]
四舍五入
 [[ 1. -0.  1.]
 [-0. -0.  0.]]
判断元素是不是number
 [[False False False]
 [False False False]]
元素相乘
 [[0.6184756  0.01753226 0.47483146]
 [0.16458453 0.05344039 0.01658039]]
元素相除
 [[1. 1. 1.]
 [1. 1. 1.]]
三元运算 [[ 1 -1  1]
 [-1 -1  1]]


In [55]:
# 元素统计
arr = np.arange(12).reshape(3,4)
print(arr)

print('均值---',np.mean(arr)) # 所有元素均值
print('最大值---',np.max(arr)) # 所有元素均值
print('最小值---',np.min(arr)) # 所有元素均值
print('最大值index---',np.argmax(arr)) # 所有元素均值
print('最小值index---',np.argmin(arr)) # 所有元素均值
print('标准差---',np.std(arr)) # 所有元素均值
print('方差---',np.var(arr)) # 所有元素均值




print(np.cumsum(arr)) # 返回一个一维数组，每个元素都是之前所有元素的 累加和

print(np.sum(arr)) # 所有元素的和

print(np.sum(arr, axis=0)) # 数组的按列统计和

print(np.sum(arr, axis=1)) # 数组的按行统计和

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
均值--- 5.5
最大值--- 11
最小值--- 0
最大值index--- 11
最小值index--- 0
标准差--- 3.452052529534663
方差--- 11.916666666666666
[ 0  1  3  6 10 15 21 28 36 45 55 66]
66
[12 15 18 21]
[ 6 22 38]


In [49]:
# 元素判断函数
arr = np.random.randn(2,3)
print(arr)

print(np.any(arr > 0)) # 任意元素大于0
print(np.all(arr > 0)) # 所有元素大于0

[[-0.37583793 -0.8285668   0.63703396]
 [ 0.41366364 -0.24593872 -0.33826527]]
True
False


In [56]:
# 元素去重和排序
arr = np.array([[1, 2, 1], [2, 3, 4]])
print(arr)

print(np.unique(arr))

[[1 2 1]
 [2 3 4]]
[1 2 3 4]


In [8]:
from random import random
arr = np.array([random() for i in range(10)])
print(arr)
# array 保留两位小数
np.round(arr,2)

[5.94912765e-01 4.23029027e-01 9.34900482e-02 3.76788352e-04
 6.94071675e-02 2.39813308e-01 2.96409300e-01 3.65358060e-01
 5.03750816e-01 3.65555439e-01]


array([0.59, 0.42, 0.09, 0.  , 0.07, 0.24, 0.3 , 0.37, 0.5 , 0.37])