In [6]:
import pandas as pd

Series是一种类似于一维数组的 对象，由**一组数据**（各种NumPy数据类型）以及一组与之**对应的索引**（数据标签）组成。

In [7]:
# 通过list构建Series
ser_obj = pd.Series(range(10, 20))
print(ser_obj.head(3))

print(ser_obj)

print(type(ser_obj))

0    10
1    11
2    12
dtype: int64
0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
<class 'pandas.core.series.Series'>


In [8]:
# 获取数据
print(ser_obj.values)

# 获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


In [9]:
#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


In [10]:
# 索引与数据的对应关系不被运算结果影响
print(ser_obj * 2)
print(ser_obj > 15)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [13]:
# 通过dict构建Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)
print(ser_obj2.values)


2001    17.8
2002    20.1
2003    16.5
dtype: float64
Int64Index([2001, 2002, 2003], dtype='int64')
[17.8 20.1 16.5]


In [12]:
# name属性
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
print(ser_obj2.head())
print(ser_obj.values)


year
2001    17.8
2002    20.1
2003    16.5
Name: temp, dtype: float64


In [16]:
import numpy as np
import pandas as pd

# 通过ndarray构建DataFrame
array = np.random.randn(5,4)
print(array)

df_obj = pd.DataFrame(array)
print(df_obj.head())

[[ 2.56323086  0.93566103 -0.15502412  0.46584405]
 [ 0.26458452 -0.73430887  0.68519469 -1.73491781]
 [ 0.21876966  0.59376934 -0.67899901  0.36490313]
 [ 0.08977066 -1.03704757 -1.64582722  0.08020139]
 [ 0.52852333 -0.25906521  0.88419452  1.2260577 ]]
          0         1         2         3
0  2.563231  0.935661 -0.155024  0.465844
1  0.264585 -0.734309  0.685195 -1.734918
2  0.218770  0.593769 -0.678999  0.364903
3  0.089771 -1.037048 -1.645827  0.080201
4  0.528523 -0.259065  0.884195  1.226058


In [17]:
# 通过dict构建DataFrame
dict_data = {'A': 1, 
             'B': pd.Timestamp('20170426'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'ITCast' }
#print dict_data
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)

   A          B    C  D       E       F
0  1 2017-04-26  1.0  3  Python  ITCast
1  1 2017-04-26  1.0  3    Java  ITCast
2  1 2017-04-26  1.0  3     C++  ITCast
3  1 2017-04-26  1.0  3       C  ITCast


In [18]:
# 通过列索引获取列数据
print(df_obj2['A'])
print(type(df_obj2['A']))

print(df_obj2.A)

0    1
1    1
2    1
3    1
Name: A, dtype: int64
<class 'pandas.core.series.Series'>
0    1
1    1
2    1
3    1
Name: A, dtype: int64


In [19]:
# 增加列
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

   A          B    C  D       E       F  G
0  1 2017-04-26  1.0  3  Python  ITCast  7
1  1 2017-04-26  1.0  3    Java  ITCast  7
2  1 2017-04-26  1.0  3     C++  ITCast  7
3  1 2017-04-26  1.0  3       C  ITCast  7


In [20]:
# 删除列
del(df_obj2['G'] )
print(df_obj2.head())

   A          B    C  D       E       F
0  1 2017-04-26  1.0  3  Python  ITCast
1  1 2017-04-26  1.0  3    Java  ITCast
2  1 2017-04-26  1.0  3     C++  ITCast
3  1 2017-04-26  1.0  3       C  ITCast


# pandas 索引操作

In [21]:
print(type(ser_obj.index))
print(type(df_obj2.index))
print(df_obj2.index)

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.numeric.Int64Index'>
Int64Index([0, 1, 2, 3], dtype='int64')


In [ ]:
# 索引对象不可变，为了保证数据安全
df_obj2.index[0] = 2

In [25]:
# series索引
ser_obj = pd.Series(range(5), index = ['a', 'b', 'c', 'd', 'e'])
print(ser_obj.head())

a    0
b    1
c    2
d    3
e    4
dtype: int64


In [28]:
# 行索引
# 两种方式下标或者键：ser_obj[‘label’], ser_obj[pos]
print(ser_obj['b'])
print(ser_obj[0])

1
0


In [ ]:
# 切片索引（不同于python的列表的切片，是包含终止索引的）
print(ser_obj[1:3])
print(ser_obj['b':'d'])

In [29]:
# 不连续索引
print(ser_obj[[0, 2, 4]])
print(ser_obj[['a', 'e']])

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64


In [32]:
# 布尔索引
ser_bool = ser_obj > 2
print(ser_bool)
print('---\n',ser_obj[ser_bool])

print(ser_obj[ser_obj > 2])

a    False
b    False
c    False
d     True
e     True
dtype: bool
---
 d    3
e    4
dtype: int64
d    3
e    4
dtype: int64


In [34]:
import numpy as np

df_obj = pd.DataFrame(np.random.randn(5,4), columns = ['a', 'b', 'c', 'd'])
print(df_obj.head())
print(df_obj.values)
print(df_obj.index)
print(df_obj.columns)

          a         b         c         d
0 -1.108643  1.357491  1.259737 -2.263446
1  1.017911 -0.845725 -1.615744  0.664635
2 -0.907168 -1.394682  0.735338  1.819155
3  0.398520 -0.957597 -0.695398 -0.492383
4  0.878395 -1.457682  0.005367  0.804158
[[-1.10864272  1.35749113  1.25973718 -2.26344556]
 [ 1.01791065 -0.84572489 -1.6157437   0.66463461]
 [-0.90716831 -1.39468208  0.7353378   1.81915469]
 [ 0.39851961 -0.9575969  -0.6953981  -0.49238273]
 [ 0.87839503 -1.45768174  0.00536671  0.80415783]]
RangeIndex(start=0, stop=5, step=1)
Index(['a', 'b', 'c', 'd'], dtype='object')


In [47]:
# 列索引
#print(df_obj['a'],'\n') # 返回Series类型
print(df_obj)
print(df_obj['a']) # 返回DataFrame类型
#print(type(df_obj[[0]])) # 返回DataFrame类型

          a         b         c         d
0 -1.108643  1.357491  1.259737 -2.263446
1  1.017911 -0.845725 -1.615744  0.664635
2 -0.907168 -1.394682  0.735338  1.819155
3  0.398520 -0.957597 -0.695398 -0.492383
4  0.878395 -1.457682  0.005367  0.804158
0   -1.108643
1    1.017911
2   -0.907168
3    0.398520
4    0.878395
Name: a, dtype: float64
